repository = "sentence-transformers/all-MiniLM-L6-v2"
revision = "1110a243fdf4706b3f48f1d95db1a4f5529b4d41"
destination = "models/sentence-transformers/all-MiniLM-L6-v2"
embedding_dimensions = 384

files = [
  "1_Pooling/config.json",
  "config.json",
  "config_sentence_transformers.json",
  "data_config.json",
  "model.safetensors",
  "modules.json",
  "sentence_bert_config.json",
  "special_tokens_map.json",
  "tokenizer.json",
  "tokenizer_config.json",
  "vocab.txt",
]

[minimum_size_bytes]
"model.safetensors" = 80000000
