#!/usr/bin/env python3
"""Generate a release title, tag, and dependency-aware release notes."""

from __future__ import annotations

import os
from pathlib import Path
import re
import sys
import tomllib


ROOT = Path(__file__).resolve().parents[1]
GENERATED_MARKER = "<!-- generated by scripts/release_metadata.py -->"
BUILD_NOTES_MARKER = "<!-- original build notes -->"

DISPLAY_NAMES = {
    "docs-and-eda": "Docs and EDA",
    "matlab": "MATLAB",
    "optimisation-and-solver-gurobi": "Optimisation and Solver (Gurobi)",
    "optimisation-and-solver-oss": "Optimisation and Solver (OSS)",
    "pisp": "PISP.jl",
    "power-systems": "Power Systems",
    "power-systems-dynamics": "Power Systems Dynamics",
    "semantic-search": "Semantic Search",
}


def die(message: str) -> None:
    raise SystemExit(message)


def load_toml(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def display_name(environment_name: str) -> str:
    return DISPLAY_NAMES.get(
        environment_name,
        environment_name.replace("-", " ").title(),
    )


def python_version(pyproject: dict) -> str:
    constraint = str(pyproject.get("project", {}).get("requires-python", ""))
    match = re.search(r"(\d+)\.(\d+)", constraint)
    if not match:
        die(f"Cannot determine Python version from: {constraint!r}")
    return f"{match.group(1)}.{match.group(2)}"


def normalise_python_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def julia_dependencies(project: dict, manifest: dict) -> list[tuple[str, str]]:
    resolved: list[tuple[str, str]] = []
    manifest_dependencies = manifest.get("deps", {})

    for name, uuid in sorted(project.get("deps", {}).items()):
        entries = manifest_dependencies.get(name, [])
        if isinstance(entries, dict):
            entries = [entries]
        entry = next(
            (candidate for candidate in entries if candidate.get("uuid") == uuid),
            entries[0] if entries else None,
        )
        if entry is None:
            die(f"Direct Julia dependency is absent from Manifest.toml: {name}")
        version = entry.get("version")
        if not version:
            die(f"Direct Julia dependency has no resolved version: {name}")
        resolved.append((name, str(version)))

    return resolved


def python_dependencies(pyproject: dict, lock: dict) -> list[tuple[str, str]]:
    locked_packages = {
        normalise_python_name(str(package["name"])): package
        for package in lock.get("package", [])
        if package.get("name")
    }
    resolved: list[tuple[str, str]] = []

    for requirement in pyproject.get("project", {}).get("dependencies", []):
        match = re.match(r"\s*([A-Za-z0-9_.-]+)(?:\[[^]]+\])?\s*==\s*([^;\s]+)", requirement)
        if not match:
            die(f"Python dependency is not exactly pinned: {requirement}")
        name, declared_version = match.groups()
        package = locked_packages.get(normalise_python_name(name))
        if package is None:
            die(f"Direct Python dependency is absent from uv.lock: {name}")
        locked_version = str(package.get("version", ""))
        if not locked_version:
            die(f"Direct Python dependency has no locked version: {name}")
        if locked_version != declared_version:
            die(
                f"Python dependency version mismatch for {name}: "
                f"pyproject.toml has {declared_version}, uv.lock has {locked_version}"
            )
        resolved.append((name, locked_version))

    return sorted(resolved, key=lambda item: item[0].lower())


def markdown_table(rows: list[tuple[str, str]]) -> str:
    lines = ["| Package | Resolved version |", "|---|---:|"]
    lines.extend(f"| {name} | {version} |" for name, version in rows)
    return "\n".join(lines)


def original_build_notes(notes_file: Path) -> str:
    if not notes_file.is_file():
        return ""
    notes = notes_file.read_text(encoding="utf-8").strip()
    if notes.startswith(GENERATED_MARKER):
        if BUILD_NOTES_MARKER in notes:
            notes = notes.split(BUILD_NOTES_MARKER, 1)[1].strip()
        else:
            notes = ""
    return notes


def pisp_details(
    project: dict,
    manifest: dict,
    dependencies: list[tuple[str, str]],
) -> tuple[str | None, str | None]:
    versions = dict(dependencies)
    version = versions.get("PISP")
    source = project.get("sources", {}).get("PISP", {})
    revision = source.get("rev")

    entries = manifest.get("deps", {}).get("PISP", [])
    if isinstance(entries, dict):
        entries = [entries]
    if entries:
        revision = revision or entries[0].get("repo-rev")

    if version and revision and re.fullmatch(r"v?\d+\.\d+\.\d+", str(revision)):
        if str(revision).removeprefix("v") != version:
            die(
                f"PISP source revision {revision} does not match "
                f"the resolved package version {version}"
            )
    return version, str(revision) if revision else None


def main() -> None:
    if len(sys.argv) != 2:
        die(f"usage: {sys.argv[0]} ENVIRONMENT_NAME")

    environment_name = sys.argv[1]
    source_environment = ROOT / "environments" / environment_name
    dist_dir = ROOT / "dist" / environment_name
    notes_file = dist_dir / "RELEASE_NOTES.md"
    run_number = os.environ.get("GITHUB_RUN_NUMBER", "local")
    run_attempt = os.environ.get("GITHUB_RUN_ATTEMPT", "1")

    if not dist_dir.is_dir():
        die(f"Build output not found: {dist_dir}")

    if environment_name == "runtime":
        julia_version = os.environ.get("JULIA_VERSION", "1.12.4")
        tag = f"julia-{julia_version}-runtime-run-{run_number}-{run_attempt}"
        title = f"Julia {julia_version} runtime for Linux x86-64"
        sections = [
            "## Runtime",
            "",
            "| Runtime | Version | Platform |",
            "|---|---:|---|",
            f"| Julia | {julia_version} | Linux x86-64 |",
            "",
        ]
        introduction = "The runtime version below is the version packaged by this release."
    else:
        project_path = source_environment / "Project.toml"
        manifest_path = source_environment / "Manifest.toml"
        pyproject_path = source_environment / "pyproject.toml"
        lock_path = source_environment / "uv.lock"

        has_julia = project_path.is_file() and manifest_path.is_file()
        has_python = pyproject_path.is_file() and lock_path.is_file()
        has_partial_julia = project_path.is_file() != manifest_path.is_file()
        has_partial_python = pyproject_path.is_file() != lock_path.is_file()

        if has_partial_julia:
            die(f"{environment_name}: Project.toml and Manifest.toml must both exist")
        if has_partial_python:
            die(f"{environment_name}: pyproject.toml and uv.lock must both exist")
        if not has_julia and not has_python:
            die(f"{environment_name}: no supported environment metadata found")

        name = display_name(environment_name)
        runtime_labels: list[str] = []
        tag_parts: list[str] = []
        sections = []
        pisp_version: str | None = None

        if has_julia:
            project = load_toml(project_path)
            manifest = load_toml(manifest_path)
            julia_version = str(manifest.get("julia_version", ""))
            if not julia_version:
                die(f"{environment_name}: julia_version missing from Manifest.toml")
            dependencies = julia_dependencies(project, manifest)
            pisp_version, pisp_revision = pisp_details(project, manifest, dependencies)

            runtime_labels.append(f"Julia {julia_version}")
            tag_parts.extend(["julia", julia_version])
            sections.extend(
                [
                    "## Julia runtime",
                    "",
                    f"- Julia: **{julia_version}**",
                    f"- Direct dependencies: **{len(dependencies)}**",
                    "",
                ]
            )
            if pisp_version:
                sections.extend(
                    [
                        "## PISP.jl",
                        "",
                        f"- Resolved package version: **{pisp_version}**",
                        f"- Source revision: `{pisp_revision or 'not specified'}`",
                        "",
                    ]
                )
            sections.extend(
                [
                    "## Direct Julia dependencies",
                    "",
                    "Declared in `Project.toml` and resolved by `Manifest.toml`.",
                    "",
                    markdown_table(dependencies),
                    "",
                ]
            )

        if has_python:
            pyproject = load_toml(pyproject_path)
            lock = load_toml(lock_path)
            version = python_version(pyproject)
            dependencies = python_dependencies(pyproject, lock)

            runtime_labels.append(f"Python {version}")
            tag_parts.extend(["py", version.replace(".", "")])
            sections.extend(
                [
                    "## Python runtime",
                    "",
                    f"- Python: **{version}**",
                    f"- Direct dependencies: **{len(dependencies)}**",
                    "",
                    "## Direct Python dependencies",
                    "",
                    "Declared in `pyproject.toml` and resolved by `uv.lock`.",
                    "",
                    markdown_table(dependencies),
                    "",
                ]
            )

        runtime_text = " and ".join(runtime_labels)
        title_name = f"PISP.jl v{pisp_version}" if pisp_version else name
        title = f"{title_name} environment for {runtime_text}"

        if has_julia:
            tag = f"julia-{tag_parts[1]}-{environment_name}"
            if has_python:
                tag += f"-py{tag_parts[-1]}"
        else:
            tag = f"{environment_name}-py{tag_parts[-1]}"
        tag += f"-run-{run_number}-{run_attempt}"
        introduction = (
            "The versions below are read from the committed environment files "
            "used by this release."
        )

    build_notes = original_build_notes(notes_file)
    if build_notes:
        sections.extend(
            [
                "## Build and verification",
                "",
                BUILD_NOTES_MARKER,
                build_notes,
                "",
            ]
        )

    notes = "\n".join(
        [
            GENERATED_MARKER,
            introduction,
            "",
            *sections,
        ]
    ).rstrip() + "\n"
    notes_file.write_text(notes, encoding="utf-8")

    print(tag)
    print(title)


if __name__ == "__main__":
    main()